# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@google/gemini-cli-0.1.1" = {
      name = "_at_google_slash_gemini-cli";
      packageName = "@google/gemini-cli";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@google/gemini-cli/-/gemini-cli-0.1.1.tgz";
        sha512 = "6/NGntIvC2yBUPVYeMUP0MtmNgi+uBJPi+h/RmxPKRNBD1L8h+Y7VUJPpAoTi9Yl43fM6l2poPHtxwgPK1L6qA==";
      };
    };
  };
in
{
  "@anthropic-ai/claude-code" = nodeEnv.buildNodePackage {
    name = "_at_anthropic-ai_slash_claude-code";
    packageName = "@anthropic-ai/claude-code";
    version = "1.0.34";
    src = fetchurl {
      url = "https://registry.npmjs.org/@anthropic-ai/claude-code/-/claude-code-1.0.34.tgz";
      sha512 = "9mQd8hodE5/RxZnsWUCdLzqGUKuCzBczrfc2QfxrNSlvUFpOgTzjT1Zlww2vW9v0K1e5K9g1o08apqPl/QPmpw==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "Use Claude, Anthropic's AI assistant, right from your terminal. Claude can understand your codebase, edit files, run terminal commands, and handle entire workflows for you.";
      homepage = "https://github.com/anthropics/claude-code";
      license = "SEE LICENSE IN README.md";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  "@google/gemini-cli" = nodeEnv.buildNodePackage {
    name = "_at_google_slash_gemini-cli";
    packageName = "@google/gemini-cli";
    version = "0.1.1";
    src = fetchurl {
      url = "https://registry.npmjs.org/@google/gemini-cli/-/gemini-cli-0.1.1.tgz";
      sha512 = "6/NGntIvC2yBUPVYeMUP0MtmNgi+uBJPi+h/RmxPKRNBD1L8h+Y7VUJPpAoTi9Yl43fM6l2poPHtxwgPK1L6qA==";
    };
    dependencies = [
      sources."@google/gemini-cli-0.1.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "[![Gemini CLI CI](https://github.com/google-gemini/gemini-cli/actions/workflows/ci.yml/badge.svg)](https://github.com/google-gemini/gemini-cli/actions/workflows/ci.yml)";
      homepage = "https://github.com/google-gemini/gemini-cli#readme";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
