layerrules = true
kill_bind = "ctrl+shift+alt, h"

[launcher]
default_terminal = "kitty"
width = 650
max_items = 5
show_when_empty = true
animate_launch_ms = 250

[launcher.plugins.applications]
run_cache_weeks = 4
show_execs = true
show_actions_submenu = false

[launcher.plugins.terminal]

[launcher.plugins.shell]

[[launcher.plugins.websearch.engines]]
url = "https://www.google.com/search?q={}"
name = "Google"
key = "g"

[[launcher.plugins.websearch.engines]]
url = "https://www.youtube.com/results?search_query={}"
name = "YouTube"
key = "y"

[launcher.plugins.calc]

[windows]
scale = 8.5
workspaces_per_row = 5
strip_html_from_workspace_title = true

[windows.overview.open]
key = "Tab"
modifier = "super"

[windows.overview.navigate]
forward = "tab"

[windows.overview.navigate.reverse]
key = "grave"

[windows.overview.other]
filter_by = []
hide_filtered = false

[windows.switch.open]
modifier = "super"

[windows.switch.navigate]
forward = "tab"

[windows.switch.navigate.reverse]
key = "grave"

[windows.switch.other]
filter_by = []
hide_filtered = true
